In [1]:
import numpy as np

## Scalar

In [2]:
x = np.array(42)
x.shape

()

In [3]:
x.ndim

0

## Vector

In [4]:
x = np.array([1, 2, 3, 4, 5, 6])
x.shape

(6,)

In [5]:
x.ndim

1

## Matrix

In [6]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x.shape

(3, 3)

In [7]:
x.ndim

2

## Tensor

In [9]:
x = np.array([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]]
])

x.shape

(2, 3, 3)

In [10]:
x.ndim

3

# Reshape

In [13]:
x = np.array([
    [0, 1],
    [2, 3],
    [4, 5],
    [6, 7]
])

x.shape, x.ndim

((4, 2), 2)

In [14]:
x.reshape(8, 1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [15]:
x.reshape(2, 4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

## Transpose

In [16]:
np.transpose(x)

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [17]:
x.T

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])